# Generated by Django 5.2.7 on 2025-10-26 19:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0105_merge_subscribe_footer_notes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="subscribe_note",
        ),
        migrations.AlterField(
            model_name="user",
            name="footer_note",
            field=models.TextField(
                blank=True,
                default="Subscribe via [RSS](/rss/) / [via Email](/newsletter/).\n\nPowered by [mataroa.blog](https://mataroa.blog/).",
                help_text="Supports markdown. Appears at the bottom of your blog.",
                null=True,
            ),
        ),
    ]
