# Generated by Django 6.0rc1 on 2025-11-24 00:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0106_remove_subscribe_note"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="post_altpath_on",
            field=models.BooleanField(
                default=False,
                help_text="Serve posts under /p/ instead of /blog/.",
                verbose_name="Alternative Post Path",
            ),
        ),
    ]
