# Generated by Django 6.0 on 2026-01-03 17:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0108_alter_user_custom_domain"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="onboard",
            name="problems",
        ),
        migrations.RemoveField(
            model_name="onboard",
            name="quality",
        ),
        migrations.RemoveField(
            model_name="onboard",
            name="seo",
        ),
    ]
