# Generated by Django 6.0 on 2026-01-03 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0109_remove_onboard_problems_remove_onboard_quality_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyticpost',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
