# Generated by Django 6.0 on 2026-01-03 18:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0111_analyticpage_indexes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="about",
        ),
    ]
