# Generated by Django 6.0.1 on 2026-01-06 21:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0112_remove_user_about"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                fields=["owner", "-published_at"], name="main_post_owner_i_4d3ea0_idx"
            ),
        ),
    ]
