# Generated by Django 6.0.2 on 2026-02-16 20:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0113_post_owner_published_at_idx"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlueskyOAuthRequest",
            fields=[
                (
                    "state",
                    models.CharField(max_length=128, primary_key=True, serialize=False),
                ),
                ("authserver_iss", models.URLField()),
                ("did", models.CharField(blank=True, max_length=500, null=True)),
                ("handle", models.CharField(blank=True, max_length=500, null=True)),
                ("pds_url", models.URLField(blank=True, null=True)),
                ("pkce_verifier", models.CharField(max_length=128)),
                ("scope", models.CharField(max_length=500)),
                (
                    "dpop_authserver_nonce",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                ("dpop_private_jwk", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BlueskyOAuthSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("did", models.CharField(max_length=500)),
                ("handle", models.CharField(max_length=500)),
                ("pds_url", models.URLField()),
                ("authserver_iss", models.URLField()),
                ("access_token", models.TextField()),
                ("refresh_token", models.TextField()),
                (
                    "dpop_authserver_nonce",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                (
                    "dpop_pds_nonce",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                ("dpop_private_jwk", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
