# Generated by Django 6.0.1 on 2026-08-01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0113_post_owner_published_at_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_delisted",
            field=models.BooleanField(
                default=False,
                help_text=(
                    "Show a warning that this user's blog has been delisted from "
                    "search engines because of spam."
                ),
                verbose_name="Search engine delisted",
            ),
        ),
    ]
