# Generated by Django 6.0.2 on 2026-02-16 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0114_blueskyoauthrequest_blueskyoauthsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='blueskyoauthsession',
            name='publication_uri',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
