# Generated by Django 6.0.9 on 2026-10-08 22:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0115_user_is_redirect_grandfathered"),
    ]

    operations = [
        migrations.CreateModel(
            name="OAuthClient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("client_id", models.CharField(max_length=255, unique=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "client_type",
                    models.CharField(
                        choices=[
                            ("public", "Public"),
                            ("confidential", "Confidential"),
                        ],
                        max_length=12,
                    ),
                ),
                ("secret_hash", models.CharField(blank=True, max_length=255)),
                (
                    "redirect_uris",
                    models.TextField(
                        help_text="Exact HTTPS callback URLs, one per line."
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OAuthGrant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scope", models.CharField(max_length=100)),
                ("resource", models.URLField(max_length=2048)),
                ("redirect_uri", models.URLField(max_length=2048)),
                ("code_hash", models.CharField(max_length=64, unique=True)),
                ("code_challenge", models.CharField(max_length=43)),
                ("code_expires", models.DateTimeField()),
                ("consumed", models.BooleanField(default=False)),
                ("revoked", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.oauthclient",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OAuthToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("access_hash", models.CharField(max_length=64, unique=True)),
                ("refresh_hash", models.CharField(max_length=64, unique=True)),
                ("scope", models.CharField(max_length=100)),
                ("access_expires", models.DateTimeField()),
                ("refresh_expires", models.DateTimeField()),
                ("revoked", models.BooleanField(default=False)),
                (
                    "grant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tokens",
                        to="main.oauthgrant",
                    ),
                ),
            ],
        ),
    ]
