# Generated by Django 6.0.2 on 2026-02-16 22:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0115_blueskyoauthsession_publication_uri"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="bluesky_document_rkey",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
