# Generated by Django 6.0.9 on 2026-10-09 18:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0116_oauth"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="oauthclient",
            options={
                "verbose_name": "OAuth client",
                "verbose_name_plural": "OAuth clients",
            },
        ),
        migrations.AlterModelOptions(
            name="oauthgrant",
            options={
                "verbose_name": "OAuth grant",
                "verbose_name_plural": "OAuth grants",
            },
        ),
    ]
