"""
Django settings for mataroa project.

Generated by 'django-admin startproject' using Django 3.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os
from pathlib import Path
from urllib import parse

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY", "nonrandom_secret")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG") == "1"

LOCALDEV = os.getenv("LOCALDEV") == "1"
SIGNUPS_ENABLED = os.getenv("SIGNUPS_ENABLED", "1") == "1"

ALLOWED_HOSTS = [
    "127.0.0.1",
    "localhost",
    f".{os.getenv('DOMAIN', 'mataroa.blog')}",
    ".mataroalocal.blog",
    "*",
]

ADMINS = [os.getenv("ADMIN_EMAIL")] if os.getenv("ADMIN_EMAIL") else []

CANONICAL_HOST = os.getenv("DOMAIN", "mataroa.blog")
if LOCALDEV:
    CANONICAL_HOST = "mataroalocal.blog:8000"

CUSTOM_DOMAIN_IP = os.getenv("CUSTOM_DOMAIN_IP")

# Application definition

INSTALLED_APPS = [
    "main.apps.MainConfig",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sitemaps",
    "django.contrib.humanize",
]

MIDDLEWARE = [
    "main.middleware.speed_middleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "main.middleware.host_middleware",
]

ROOT_URLCONF = "mataroa.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "mataroa.wsgi.application"

AUTH_USER_MODEL = "main.User"

LOGIN_REDIRECT_URL = "index"
LOGOUT_REDIRECT_URL = "index"

SESSION_COOKIE_AGE = 31449600  # 60 * 60 * 24 * 7 * 52 = 1 year in seconds
SESSION_COOKIE_DOMAIN = CANONICAL_HOST.split(":")[0]  # session visible in subdomains

DATE_FORMAT = "F j, Y"
DATETIME_FORMAT = "F j, Y, P"

DATA_UPLOAD_MAX_NUMBER_FILES = 50


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

database_url = os.getenv("DATABASE_URL", "")
database_url = parse.urlparse(database_url)
# e.g. postgres://mataroa:password@127.0.0.1:5432/mataroa
database_name = database_url.path[1:]  # url.path is '/mataroa'
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": parse.unquote(database_name or ""),
        "USER": parse.unquote(database_url.username or ""),
        "PASSWORD": parse.unquote(database_url.password or ""),
        "HOST": database_url.hostname,
        "PORT": database_url.port or "",
        "CONN_MAX_AGE": 500,
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = False

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "static"
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.ManifestStaticFilesStorage",
    },
}


# Default forms.URLField scheme
# https://docs.djangoproject.com/en/5.0/ref/settings/#forms-urlfield-assume-https

FORMS_URLFIELD_ASSUME_HTTPS = True


# Email

EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
if LOCALDEV:
    EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
EMAIL_USE_TLS = True
EMAIL_HOST = "smtp.postmarkapp.com"
EMAIL_HOST_BROADCASTS = "smtp-broadcasts.postmarkapp.com"
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD")
EMAIL_PORT = 587

POSTMARK_WEBHOOK_PASSWORD = os.getenv("POSTMARK_WEBHOOK_PASSWORD")

EMAIL_FROM_HOST = CANONICAL_HOST
DEFAULT_FROM_EMAIL = f"Mataroa <admin@{EMAIL_FROM_HOST}>"
NOTIFICATIONS_FROM_EMAIL = f"Mataroa Notifications <notifications@{EMAIL_FROM_HOST}>"
SERVER_EMAIL = f"Mataroa Server <server@{EMAIL_FROM_HOST}>"
EMAIL_SUBJECT_PREFIX = "[Mataroa Notification] "


# Security middleware

if not DEBUG and not LOCALDEV:
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = "DENY"
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True


# Stripe
# https://stripe.com/docs/api

STRIPE_API_KEY = os.getenv("STRIPE_API_KEY", "")
STRIPE_PUBLIC_KEY = os.getenv("STRIPE_PUBLIC_KEY", "")
STRIPE_PRICE_ID = os.getenv("STRIPE_PRICE_ID", "")
STRIPE_WEBHOOK_SECRET = os.getenv("STRIPE_WEBHOOK_SECRET", "")


# Logging
# https://docs.djangoproject.com/en/4.1/ref/logging/#default-logging-configuration

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "filters": {
        "require_debug_false": {
            "()": "django.utils.log.RequireDebugFalse",
        },
        "require_debug_true": {
            "()": "django.utils.log.RequireDebugTrue",
        },
    },
    "formatters": {
        "django.server": {
            "()": "django.utils.log.ServerFormatter",
            "format": "[{server_time}] {message}",
            "style": "{",
        }
    },
    "handlers": {
        "console": {
            "level": "INFO",
            "filters": ["require_debug_true"],
            "class": "logging.StreamHandler",
        },
        "console_production": {
            "level": "WARNING",
            "filters": ["require_debug_false"],
            "class": "logging.StreamHandler",
        },
        "django.server": {
            "level": "INFO",
            "class": "logging.StreamHandler",
            "formatter": "django.server",
        },
        "mail_admins": {
            "level": "ERROR",
            "filters": ["require_debug_false"],
            "class": "django.utils.log.AdminEmailHandler",
        },
    },
    "loggers": {
        "django": {
            "handlers": ["console", "console_production", "mail_admins"],
            "level": "INFO",
        },
        "django.server": {
            "handlers": ["django.server"],
            "level": "INFO",
            "propagate": False,
        },
        "django.security.DisallowedHost": {
            "handlers": ["console"],
            "propagate": False,
        },
        "django.security.TooManyFilesSent": {
            "handlers": ["console", "console_production"],
            "propagate": False,
        },
        "django.security.RequestDataTooBig": {
            "handlers": ["console", "console_production"],
            "propagate": False,
        },
        "main": {
            "handlers": ["console", "console_production"],
            "level": "INFO",
            "propagate": False,
        },
    },
}


# Optional first-party ChatGPT/MCP integration. Nothing is registered or granted
# on startup. Enable only after migrations and explicit OAuth client registration.
MATAROA_CHATGPT_ENABLED = os.getenv("MATAROA_CHATGPT_ENABLED", "0") == "1"
MATAROA_MCP_ISSUER_URL = os.getenv(
    "MATAROA_MCP_ISSUER_URL", f"https://{CANONICAL_HOST}"
).rstrip("/")
MATAROA_MCP_RESOURCE_URL = f"{MATAROA_MCP_ISSUER_URL}/mcp"
MATAROA_CHATGPT_CLIENT_IDS = tuple(
    value.strip()
    for value in os.getenv("MATAROA_CHATGPT_CLIENT_IDS", "").split(",")
    if value.strip()
)

if MATAROA_CHATGPT_ENABLED:
    from django.core.exceptions import ImproperlyConfigured

    _mcp_issuer = parse.urlsplit(MATAROA_MCP_ISSUER_URL)
    if (
        _mcp_issuer.scheme != "https"
        or _mcp_issuer.netloc != CANONICAL_HOST
        or _mcp_issuer.path
        or _mcp_issuer.query
        or _mcp_issuer.fragment
        or _mcp_issuer.username
        or _mcp_issuer.password
    ):
        raise ImproperlyConfigured(
            "MATAROA_MCP_ISSUER_URL must be the canonical HTTPS origin, without a path."
        )
    INSTALLED_APPS += ["oauth2_provider"]
    OAUTH2_PROVIDER = {
        "OAUTH2_VALIDATOR_CLASS": "mataroa.oauth.MataroaOAuth2Validator",
        "SCOPES": {
            "blog:read": "Read your posts, drafts, pages, and blog comments",
            "drafts:write": "Create and edit unpublished drafts",
            "posts:publish": "Publish or schedule approved drafts",
        },
        "DEFAULT_SCOPES": ["blog:read"],
        "PKCE_REQUIRED": True,
        "ACCESS_TOKEN_EXPIRE_SECONDS": 3600,
        "AUTHORIZATION_CODE_EXPIRE_SECONDS": 120,
        "REFRESH_TOKEN_EXPIRE_SECONDS": 30 * 24 * 60 * 60,
        "ROTATE_REFRESH_TOKEN": True,
        "REFRESH_TOKEN_REUSE_PROTECTION": True,
        "REFRESH_TOKEN_GRACE_PERIOD_SECONDS": 0,
        "ALLOWED_REDIRECT_URI_SCHEMES": ["https"],
        "ALLOW_URI_WILDCARDS": False,
        "REQUEST_APPROVAL_PROMPT": "force",
        "DCR_ENABLED": False,
        "CIMD_ENABLED": False,
        "OIDC_ENABLED": False,
        "OIDC_ISS_ENDPOINT": MATAROA_MCP_ISSUER_URL,
        "OAUTH2_RESPONSE_TYPES_SUPPORTED": ["code"],
        "OAUTH2_GRANT_TYPES_SUPPORTED": ["authorization_code", "refresh_token"],
        "OAUTH2_TOKEN_ENDPOINT_AUTH_METHODS_SUPPORTED": [
            "client_secret_basic",
            "client_secret_post",
            "none",
        ],
        "OAUTH2_PROTECTED_RESOURCE_IDENTIFIER": MATAROA_MCP_RESOURCE_URL,
        "OAUTH2_PROTECTED_RESOURCE_AUTHORIZATION_SERVERS": [MATAROA_MCP_ISSUER_URL],
        "OAUTH2_PROTECTED_RESOURCE_NAME": "Mataroa ChatGPT plugin",
        "OAUTH2_PROTECTED_RESOURCE_BEARER_METHODS_SUPPORTED": ["header"],
        "RESOURCE_SERVER_TOKEN_RESOURCE_VALIDATOR": "mataroa.oauth.exact_resource_validator",
        "COMPLIANT_BCP_RFC9700_IMPLICIT_GRANT": True,
        "COMPLIANT_BCP_RFC9700_PASSWORD_GRANT": True,
        "COMPLIANT_BCP_RFC9700_PKCE_METHOD": True,
        "COMPLIANT_BCP_RFC9700_ACCESS_TOKEN_TRANSPORT": True,
        "COMPLIANT_BCP_RFC9700_AUTHZ_RESPONSE_ISS": True,
        "COMPLIANT_BCP_RFC9700_TOKEN_STORAGE": True,
        "COMPLIANT_BCP_RFC9700_REFRESH_TOKEN": True,
        "COMPLIANT_BCP_RFC9700_REDIRECT_URI_SCHEME": True,
        "COMPLIANT_BCP_RFC9700_REDIRECT_URI_MATCHING": True,
        "COMPLIANT_BCP_RFC9700_PKCE_REQUIRED": True,
    }
